### ISSUE TITLE
How to decode `callData`?

### ISSUE THREAD

**Issue by v0n0** [protofire/opensea-wyvern-exchange-subgraph#1]
Trying to find which NFT is for sale. In theory for a `SELL` order it should be containing parameters in this format: address, address, uint256, uint256. But I wasn't successful in decoding. Do you know the right format for `callData` in a `SELL` order?

Also, are you going to publish the subgraph source code?

**Comment by cold-briu** [comment]
The subgraph source code is on dev branch.
I'm also stuck on that. Let me get some help

**Comment by cold-briu** [comment]
hi @v0n0 the current main branch contains a call data decoder made by @xenoliss.
Please be aware that it keeps breaking at some point but gives more info about how simple orders and bundle orders are decoded.
